client:
  domain:
    api:
    - www.jmapiproxyxxx.one
    - www.jmeadpoolcdn.one
    - www.jmeadpoolcdn.life
dir_rule:
  base_dir: data/pictures/benzi/temp627896
  rule: Bd
download:
  image:
    suffix: .png
  threading:
    image: 3
    photo: 1
