noResMatch1:    #除去艾特内容，与这些关键词 完全匹配 的消息，将不会触发ai回复
  - 周易
  - 天文
  - 诗经
  - 摸鱼
  - 新闻
  - 彩色小人
  - 原神
  - 查询
  - 方舟十连
  - 运势
  - 今日塔罗
  - 星铁十连
  - 角色
  - 可用角色模板
  - 星座
  - 帮助
  - 群列表
  - 菜单
  - 功能
  - 开始对话
  - 退出
  - 随机奥术
  - 本月新作
  - /clear
  - /help
  - help
  - 签到
  - gal
  - galgame推荐
  - Galgame推荐
  - 攻击
  - 测试
  - test
  - 防御
  - 攻击你
  - 开始攻击
startswith: #以这些开头的，带艾特的指令将不会触发ai回复
  - 支付宝到账
  - /sbg
  - 大召唤术
  - 大召唤阵
  - 攻击
  - 开始攻击
  - gal
  - 本日
  - 随机
  - 本月
  - /
  - /娶
endswith:   #以这些结尾的，带艾特的指令将不会触发ai回复
  - 攻击
  - 开始攻击
  - gal
  - 新作
  - 群友
Regular:    #正则表达式，如匹配则不会触发ai回复
  - '(\d+)张(\w+)'
