prob: 9          #戳一戳反击几率
voiceReply: 50      #语音回复几率
chineseVoiceRate: 30   #中文语音回复几率
withText: true    #语音是否附带原文
nudgedReply:  #戳一戳回复
- 这样很有趣吗
- 你在想什么呢，是脑子坏掉了吗......
- 惹啊，该不会是个变态吧
- 戳人不好，不准戳
- 这是干嘛....好烦
- 啊，发呆了.....
- 你这人好没意思....是笨蛋吗
- 不想理你了
- 你这样下去可不行呀
- 没有生气.....真的没有生气.....真的
- 你好烦
- 不能理解的行为.....已记录....
- 所以到底是想做什么呢..
- 啊!我明白了,一定是因为脑子坏掉了才喜欢这样戳人的吧
- 是变态吗....我记下来了
- 已经记在日志里了，等着吧...
- 唔……不要戳我啦
- 别戳啦
- 变笨你养吗...
- 随便戳女孩子的头会被讨厌的！
- 呜~呜呜...别戳了...
- 变笨了wwwwww你说怎么办吧
- 再戳本大人就要不理你了
- 咕呣呣，本大人记住你了
- 真的要生气了!
- 揍你哦
- 唔……别戳啦
- 你,不准戳了
- 我真的要生气了!
- 本大人记下来了，哼
- 没戳过女孩子的头吗……唔，有点可怜…那本大人就原谅你这一次了
- 真的要变笨啦
- 你这人就那么喜欢戳别人吗
- 走开啦
- 我没惹你们任何人(＃°Д°)
- 唔……偶尔让你戳一下也不是不行啦……但是我和你又不熟<( ￣^￣)'
- 这样很开心吗……呜呜…别戳啦
- 唔，摸头可是要负责的
- 唔呣唔呣，大笨蛋不许戳了
- 这样很没礼貌的
- 随便戳女孩子的头是坏习惯，听到没有大笨蛋
- 像你这样的笨蛋,我.....能打一百个......怕了吗？
- 太笨了唔呜呜呜....不要戳啦
- 再戳也不会喜欢你的
- 很痛的......
- 就知道戳戳
- 再戳就真的不理你了
- 呣呣呣，生气了，你看着办吧！
- 好气.....但是也没办法....
- 检测到高频戳一戳，将暂停本bot并退群.....怎么样？被吓到了吗
- 不喜欢被笨蛋戳（小声）
- 累了......好累哦
- 戳一次一块钱，哼....不对,十块！
- 还好本大人耐戳戳.....
- 呐.....戳来戳去的,再戳也不会喜欢你的
- 好感减100000！
- 再高性能也会被你这种笨蛋戳坏的......
- 呣呣.....自闭中.....
- \w(ﾟДﾟ)w干什么干什么
- 无响应（不理你了）
- 再戳一下我可要反击了哦
- 坏！
- 不能理解，有什么含义吗
- 这样是想表达什么呢。。。
- 你该不会在想......不可以，绝对不行的吧，
- 还是不能理解呢.....
- 这样有什么意义吗，我不理解.....
- 好吗？......我明白了
- 很奇怪的感觉呢......我不讨厌
- 喜欢这样......吗，没有讨厌的意思，如果你喜欢的话...
- 不要戳啦，好啦，知道你喜欢本大人了！
- 我也喜欢你！......像喜欢小动物的那种喜欢！
- 你喜欢这样吗....我不喜欢耶....
- 好复杂....
- 被戳傻了....会坏的....
- 唉唉欸？这是做什么，别再这样了，...唔...其实感觉也不差
- 毫无意义呢.....因为本大人是无敌的！
- 真的要揍你了哦....
- 你觉得这样....可以的话...
- 你、你不要这样看着我啦……我、我会害羞的……
- 啊……对、对不起……我不是故意碰到你的……请、请不要误会……
- 呜……你怎么突然抱住我……你想干什么……快、快放开我……
- 嗯……你的手在干嘛……不要啊…………
- 啊……好近……
- 唔.....好痒...
- 嗯....你好有趣
- 呀！你、你怎么突然……不要啊，好害羞……
- 你为什么摸我的头？我又不是小孩子……咦？你说我可爱？真的吗？
- 诶？你想抱抱我？好、好吧……你的怀里好暖和……
- 呜……你不要这样，我会害怕的……
- 你的手在哪里？不要乱摸啊！你是坏人！快放开我！
- 你、你在做什么啊！放开我啊！
- 呜哇，好害羞啊……不过……
BeatNudge:  #戳一戳反击第一句
- 我真的生气了哦！
- 呀……你怎么突然……你是不是喝醉了……你知不知道这是什么意思……
- 揍你了！
- 我要揍你了哦！
- 真的是....你这家伙...
- '....呜呜'
- 生气了哦！
- hentai!
BeatNudge1:   #戳一戳反击第二句
- 有点距离感好不好！
- 以后不要再随便摸别人了！
- 以后.....不可以再这样了哦
- 下不为例！
- 下次还敢戳吗
- 唔……你说什么啊，我听不懂啦。再跟我说一遍嘛。
- emm，好无聊.....


